figure() 
subplot(1,4,1) 
imagesc(zeros(10))   
caxis([0,1]) 
title(sprintf("Mutual Information: %.3f \n Normalized MI: %.3f",MI_confusionmat(zeros(10)),MI_confusionmat(zeros(10)) / log(10)))
subplot(1,4,2) 
imagesc([zeros(10,1) ones(10,1) zeros(10,8)])  
title(sprintf("Mutual Information: %.3f \n Normalized MI: %.3f",MI_confusionmat([zeros(10,1) ones(10,1) zeros(10,8)]),MI_confusionmat([zeros(10,1) ones(10,1) zeros(10,8)])/log(10))) 
subplot(1,4,3)  
noisyRelation = eye(10) + .2*rand(10);
imagesc(noisyRelation) 
title(sprintf("Mutual Information: %.3f \n Normalized MI: %.3f",MI_confusionmat(noisyRelation),MI_confusionmat(noisyRelation)/log(10)))
subplot(1,4,4) 
imagesc(eye(10)) 
colorbar()  
title(sprintf("Mutual Information: %.3f \n Normalized MI: %.3f",MI_confusionmat(eye(10)),MI_confusionmat(eye(10))/log(10)))