function threePaneFitPlot(avgFR_decVar_sorted,avgFR_decVar_sortedFitResidual,avgFR_decVar_sortedFit,decVar_bins,alignmentLabel,fitLabel)
    figure()
    subplot(1,3,1)
    colormap('jet')
    imagesc(flipud(avgFR_decVar_sorted))
    colorbar()
    title("Avg PETH")
    ylabel("Neuron")
    xlim([0,40])
    xlabel(alignmentLabel)
    xticks([0 20 40])
    xticklabels([0 1000 2000])
    subplot(1,3,3)
    imagesc(flipud(avgFR_decVar_sortedFitResidual))
    colorbar()
    title(sprintf("%s residuals",fitLabel))
    ylabel("Neuron")
    xlim([0,40])
    xlabel(alignmentLabel)
    xticks([0 20 40])
    xticklabels([0 1000 2000])
    subplot(1,3,2)
    colormap('jet')
    imagesc(flipud(avgFR_decVar_sortedFit))
    colorbar()
    title(sprintf("%s fit",fitLabel))
    ylabel("Neuron")
    xlim([0,40])
    xlabel(alignmentLabel)
    xticks([1 20 40])
    xticklabels([0 1000 2000])
end

